"""
telegram_scraper.py
-------------------
Scrapes supply-chain signals from Telegram channels the account has joined.

Authentication:
    Uses a pre-generated Pyrogram session string loaded from the .env file
    (TELEGRAM_SESSION_STRING). No phone number or OTP prompt ever runs.

To generate the session string for the first time, run:
    python generate_session.py

Environment variables required (set in .env):
    TELEGRAM_API_ID          — from https://my.telegram.org/apps
    TELEGRAM_API_HASH        — from https://my.telegram.org/apps
    TELEGRAM_SESSION_STRING  — generated by generate_session.py
"""

import json
import re
import asyncio
import os

from pyrogram import Client
from pyrogram.types import Message
from dotenv import load_dotenv

from schema import create_record

# ── Load environment variables ────────────────────────────────────────────────

load_dotenv()

API_ID = int(os.getenv("TELEGRAM_API_ID", "0"))
API_HASH = os.getenv("TELEGRAM_API_HASH", "")
SESSION_STRING = os.getenv("TELEGRAM_SESSION_STRING", "")

if not API_ID or not API_HASH:
    raise EnvironmentError(
        "Missing TELEGRAM_API_ID or TELEGRAM_API_HASH in .env\n"
        "Get them from https://my.telegram.org/apps"
    )

if not SESSION_STRING:
    raise EnvironmentError(
        "Missing TELEGRAM_SESSION_STRING in .env\n"
        "Run  python generate_session.py  once to generate it."
    )

# ── Pyrogram client (no session file — uses the string directly) ──────────────

app = Client(
    name=":memory:",
    api_id=API_ID,
    api_hash=API_HASH,
    session_string=SESSION_STRING,
)

# ── Filters ───────────────────────────────────────────────────────────────────

VALID_KEYWORDS = [
    "shortage",
    "price increase",
    "fuel shortage",
    "diesel shortage",
    "petrol shortage",
    "export ban",
    "import restriction",
    "supply disruption",
    "delivery delay",
    "stock shortage",
    "crisis",
]

IGNORE_WORDS = [
    "job",
    "internship",
    "apply",
    "offer",
    "discount",
    "voucher",
    "gift",
    "bootcamp",
    "course",
    "join now",
    "limited time",
    "sale",
    "cashback",
    "credit card",
]


# ── Helpers ───────────────────────────────────────────────────────────────────

def detect_commodity(text: str) -> str:
    if any(c in text for c in ["fuel", "petrol", "diesel"]):
        return "fuel"
    if "rice" in text:
        return "rice"
    return "unknown"


def extract_price(text: str) -> float | None:
    match = re.search(r"\d+(\.\d+)?", text)
    if match:
        try:
            return float(match.group())
        except ValueError:
            pass
    return None


# ── Main scraper ──────────────────────────────────────────────────────────────

async def scrape():
    async with app:
        print("Connected to Telegram.\n")

        # Discover channels the account has joined
        print("Discovering joined channels...")
        channels = []
        async for dialog in app.get_dialogs():
            chat = dialog.chat
            if chat.type.value in ("channel", "supergroup"):
                channels.append(chat)

        if not channels:
            print("[WARNING] No channels found. Make sure the account has joined some.")
            return

        print(f"Found {len(channels)} channel(s):\n")
        for ch in channels:
            print(f"  - {ch.title}")
        print()

        os.makedirs("data", exist_ok=True)
        records_count = 0

        for chat in channels:
            try:
                print(f"Fetching messages from: {chat.title}")
                async for message in app.get_chat_history(chat.id, limit=50):
                    if not message.text:
                        continue

                    text_lower = message.text.lower()

                    # Filter out junk
                    if any(word in text_lower for word in IGNORE_WORDS):
                        continue

                    # Only keep strong supply-chain signals
                    if not any(kw in text_lower for kw in VALID_KEYWORDS):
                        continue

                    commodity = detect_commodity(text_lower)
                    price = extract_price(text_lower)

                    try:
                        record = create_record(
                            source="telegram",
                            commodity=commodity,
                            location="unknown",
                            text=message.text,
                            price=price,
                            signal_type="behavior",
                            confidence=0.6,
                        )
                        print(json.dumps(record, indent=2))

                        with open("data/telegram_data.json", "a", encoding="utf-8") as f:
                            f.write(json.dumps(record) + "\n")

                        records_count += 1

                    except Exception as e:
                        print(f"[Schema/Save Error] {e}")

            except Exception as e:
                print(f"[Channel Error] Failed to scrape '{chat.title}': {e}")
                continue

        print(f"\nScraping complete. Total records saved: {records_count}")


if __name__ == "__main__":
    try:
        asyncio.run(scrape())
    except KeyboardInterrupt:
        print("Scraper stopped by user.")
